log:
    verbose: false

openai:
    api_base: https://one-api.devcxl.cn/v1
    api_keys:
        - sk-7f0QuciXQwHxeQRC1b35535794384c37A581C1088aC41849
    model: gpt-4
    history: 10
    default_prompt: 'You are a helpful assistant, and your assistance will be crucial for the other party in the next steps.'
