on:
    push:
        branches:
            - dev

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v3
            -   name: Set up Python 3.9
                uses: actions/setup-python@v3
                with:
                    python-version: 3.9

            -   name: Install dependencies
                run: |
                    python -m pip install --upgrade pip
                    pip install -r requirements.txt
                    pip install git+https://github.com/devcxl/wechat-api.git@dev

            -   name: Build package
                run: |
                    pyinstaller wechatbot.spec

            -   uses: actions/upload-artifact@v3
                with:
                    name: wechatbot
                    path: dist/wechatbot